projects/testing-library/src/lib/testing-library.ts
projects/testing-library/tests/component-provider/component-provider.spec.ts

fix: override component providers

---

README.md
package.json
projects/jest-utils/ng-package.json
projects/jest-utils/ng-package.prod.json
projects/jest-utils/package.json
projects/testing-library/migrations/tsconfig.migrations.json
projects/testing-library/ng-package.json
projects/testing-library/ng-package.prod.json
projects/testing-library/package.json
projects/testing-library/src/lib/models.ts
projects/testing-library/src/lib/testing-library.ts
projects/testing-library/src/public_api.ts
projects/testing-library/tests/migration/4_0_0.spec.ts
src/app/app.component.spec.ts
tsconfig.json
yarn.lock

Closes #13 
Reference: testing-library/dom-testing-library#260
You must update all imports from '@angular-extensions/testing-library' to '@testing-library/angular'

feat: initial release of scoped package

---

projects/testing-library/src/lib/testing-library.ts

See issue: https://github.com/testing-library/angular-testing-library/issues/29

fix render functions typing

---

projects/testing-library/src/lib/testing-library.ts

fix: fallfback to TestBed.get if inject doesn't exist

---

package.json
projects/testing-library/package.json

feat: support TypeScript 4

---

projects/testing-library/src/lib/testing-library.ts

… get-query inside replaceFindWithFindAndDetectChanges

fix: add custom queries to render result

---

apps/example-app/app/app.module.ts
apps/example-app/app/examples/15-dialog.component.spec.ts
apps/example-app/app/examples/15-dialog.component.ts
package.json

docs: add dialog example

---

CONTRIBUTING.md

`npm run test:lib` and `test:app` are not found.

docs: use the correct testing command

---

projects/testing-library/src/lib/testing-library.ts

Fixes https://github.com/testing-library/angular-testing-library/issues/222

fix: rerender with template

---

apps/example-app/src/app/app-routing.module.ts
apps/example-app/src/app/app.module.ts
apps/example-app/src/app/examples/09-router.spec.ts
apps/example-app/src/app/examples/09-router.ts

test: refactor router test

---

projects/testing-library/src/lib/testing-library.ts
projects/testing-library/tests/issues/issue-346.spec.ts

fix: regression autoDetectChanges

---

projects/testing-library/package.json

fix: update Angular peerDependencies to 15

---

projects/testing-library/tests/issues/issue-386.spec.ts

test: add test case for #386

---

README.md

add version compatibility

---

projects/testing-library/src/lib/testing-library.ts
projects/testing-library/tests/issues/issue-398-component-without-host-id.spec.ts

fix: cleanup components without id

---

apps/example-app/src/app/examples/21-deferable-view.component.ts
apps/example-app/src/app/examples/21-deferable-view.spec.ts
projects/testing-library/src/lib/models.ts
projects/testing-library/src/lib/testing-library.ts
projects/testing-library/tests/defer-blocks.spec.ts

feat: add methods to test deferrable views

---

README.md

docs: Fix example (#433)

---

.github/workflows/ci.yml
package.json
projects/testing-library/package.json

New version of @testing-library/dom changes various roles. Check out the changed tests in testing-library/dom-testing-library@2c57055 to get an overview about what changed.

feat: upgrade @testing-library/dom to v10

---

README.md
projects/testing-library/package.json
projects/testing-library/schematics/migrations/dtl-as-dev-dependency/index.spec.ts
projects/testing-library/schematics/migrations/dtl-as-dev-dependency/index.ts
projects/testing-library/schematics/migrations/migration.json
projects/testing-library/schematics/migrations/migrations.json
projects/testing-library/schematics/ng-add/index.ts
projects/testing-library/test-setup.ts
projects/testing-library/tsconfig.lib.prod.json
projects/testing-library/tsconfig.schematics.json

Release 17.0

---

apps/example-app/src/app/examples/02-input-output.spec.ts
apps/example-app/src/app/examples/22-signal-inputs.component.spec.ts

docs: use on in docs

---

projects/testing-library/src/lib/models.ts

fix: do not import OutputRef

---

projects/testing-library/src/lib/models.ts

chore: deprecate componentProperties

---

projects/testing-library/tests/issues/issue-493.spec.ts

docs: add test case for #493
