testing-library/angular-testing-library

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/counter/counter.spec.ts
Moved object destructuring with default values to the function implementation.
Sorry, did not see any guidelines for contribution :/
closes #17
> feat: use render without render options

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render.spec.ts
- projects/testing-library/tests/wrapper.spec.ts
Use the `ignoreComponentDeclaration` option to exclude the component to be automatically be added as a declaration.
Closes #27
> fix: allow component declarations in modules

- projects/testing-library/src/jest-utils/create-mock.ts
- projects/testing-library/src/jest-utils/index.ts
- projects/testing-library/tests/jest-utils/create-mock.spec.ts
- projects/testing-library/tests/providers/module-provider.spec.ts
The createMock function creates a mock object for an Angular type
Use provideMock to create an Angular provider for the type
> feat(jest): add createMock

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/src/lib/user-events/index.ts
- projects/testing-library/src/lib/user-events/type.ts
- projects/testing-library/src/public_api.ts
- projects/testing-library/tests/user-events/type.spec.ts
- src/app/__snapshots__/app.component.spec.ts.snap
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
This PR adds a `type` function to set an input's value - inspiration from https://github.com/testing-library/user-event.
For example:
```ts
const component = render(AppComponent);
component.type(component.getByTestId('input'), 'Oh, hello!');
```
Has some options:
- By default each char gets inputted individually but it's configurable to input the value at once with `allAtOnce`:
```
const component = render(AppComponent);
component.type(component.getByTestId('input'), 'Oh, hello!', { allAtOnce: true });
``` 
- Add a delay for each input with `delay` (in ms):
```
const component = render(AppComponent);
component.type(component.getByTestId('input'), 'Oh, hello!', { delay: 100 });
``` 
cc @d3lm
> feat: add component.type function

- projects/testing-library/package.json
Recent features (notably #40 and #48) have added additional peer dependencies that had not been added to the package.json. This is an issue when running under Bazel, where anything you do not explicitly list as a dependency is unavailable. Bazel works out the dependencies from package.json when you depend on an NPM package, thus resolving this for you when the (peer)dependencies are listed correctly.
I'm not sure if I can reproduce this in a plain Angular CLI project for you, but if needed I can provide a simple Bazel example showcasing the behaviour.
> fix: add peer dependencies

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/detect-changes.spec.ts
- projects/testing-library/tests/fire-event.spec.ts
The `blur` event fired from `type` throws when a fixture is already destroyed.
This PR adds a check to see if the fixture isn't destroyed before calling `detectChanges`.
> fix: don't call detectChanges when fixture is destroyed

- .circleci/config.yml
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render.spec.ts
- projects/testing-library/tests/rerender.spec.ts
> feat: add rerender function

- package.json
- src/app/examples/00-single-component.spec.ts
- src/app/examples/01-nested-component.spec.ts
- src/app/examples/02-input-output.spec.ts
- src/app/examples/03-forms.spec.ts
- src/app/examples/04-forms-with-material.spec.ts
- src/app/examples/05-component-provider.spec.ts
- src/app/examples/06-with-ngrx-store.spec.ts
- src/app/examples/07-with-ngrx-mock-store.spec.ts
- src/app/examples/08-directive.spec.ts
- src/app/examples/09-router.spec.ts
- src/app/examples/10-inject-token-dependency.spec.ts
- yarn.lock
The Testing Library encourages the usage of `screen` to query DOM elements.
See https://testing-library.com/docs/dom-testing-library/api-queries#screen for more info.
> refactor: use screen to query elements

- package.json
- projects/testing-library/package.json
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/wait.spec.ts
- yarn.lock
Updates DOM Testing Library.
Adds the `wait` method and deprecates the `waitForDomChange` and `waitForElement` methods.
> feat: update DOM Testing Library

- projects/jest-utils/tests/create-mock.spec.ts
- projects/testing-library/tests/render.spec.ts
`TestBed.get` is deprecated in favor of `TestBed.inject`
> fix: use testbed.inject instead of testbed.get

- src/app/examples/11-ng-content.spec.ts
- src/app/examples/11-ng-content.ts
Closes #78 
I have added an example, it's a bit different from my demo exposed in #78 but I think it shows better the use-case. Feel free to comment how improve the use-case :smile:
I can't test if my tests works because I think that `yarn test:app` is broken on my side and I don't know why :sweat_smile:
> test: add ng-content example

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/src/lib/user-events/index.ts
- projects/testing-library/src/public_api.ts
- projects/testing-library/tsconfig.lib.json
> fix: ES2015 for karma tests

- projects/testing-library/src/lib/testing-library.ts
- src/app/examples/09-router.spec.ts
- src/app/examples/09-router.ts
> fix: extract router params in navigate

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/wait-for-element-to-be-removed.spec.ts
- projects/testing-library/tests/wait-for.spec.ts
> fix: patch waitFor functions to trigger a change detection cycle

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render.spec.ts
- projects/testing-library/tests/rerender.spec.ts
This PR adds support for ngOnChanges lifecycle hook. `render` and `rerender` functions will automatically call `ngOnChanges` with correct arguments on component instance if defined.
In case of initial render the `ngOnChanges` is called before `ngOnInit` - the same behavior as in real Angular runtime.
related issues: #56
> feat: support component's ngOnChanges lifecycle hook

- jest.base.config.js
- projects/jest.lib.config.js
- projects/setupJest.ts
- projects/testing-library/src/lib/config.ts
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/src/public_api.ts
- projects/testing-library/tests/config.spec.ts
- projects/testing-library/tests/render.spec.ts
- src/app/examples/03-forms.spec.ts
- src/app/examples/03-forms.ts
- src/app/examples/04-forms-with-material.spec.ts
- src/app/examples/04-forms-with-material.ts
- src/jest.app.config.js
- src/setupJest.ts
- test.ts
Allows the `configure` method to be used to add frequently used modules.
This can be helpful for example setting the forms module at a global level instead of importing the module in every test.
```ts
beforeEach(() => {
configure({
defaultImports: [ReactiveFormsModule],
});
});
```
> feat: add imports option to configure

- .circleci/config.yml
> build: fix the release artifact

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/find-by.spec.ts
- projects/testing-library/tests/navigate.spec.ts
> fix: call navigate correctly without queryparams

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/rerender.spec.ts
Closes #157.
PS: After opening the issue #157, I noticed that there's an open issue related to this in angular repo: https://github.com/angular/angular/issues/12313.
> fix: trigger change detection cycle on rerender

- apps/example-app/app/examples/README.md
- jest.config.js
Fixes deprecation warnings:
```
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
ts-jest[config] (WARN) The configuration for astTransformers as string[] is deprecated and will be removed in ts-jest 27. Please define your custom AST transformers in a form of an object. More information you can check online documentation https://kulshekhar.github.io/ts-jest/user/config/astTransformers
```
> Update docs and jest config

- README.md
Hello, 
I was reading #162 and also found useful to have a FAQ section and have included the question mentioned in the issue as the first one. Hope this helps!
> docs: add FAQ section

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
Port of https://github.com/testing-library/react-testing-library/pull/833
> fix(types): allow all elements

- apps/example-app/app/examples/14-async-component.spec.ts
- apps/example-app/app/examples/14-async-component.ts
> docs: add async component example

- projects/jest-utils/src/lib/create-mock.ts
- projects/jest-utils/tsconfig.lib.json
- projects/testing-library/tsconfig.lib.json
Allow the users to create a mock with default values
```
createMockWithValues(MyService,
{
isCreated$: new ReplaySubject(1)
})
```
> Create mock with values

- projects/testing-library/src/lib/testing-library.ts
This way we can support Angular version 7 and below.
> fix: fallback to TestBed.get

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/issues/188.spec.ts
- projects/testing-library/tests/render.spec.ts
> fix: invoke ngOnChanges when initial value is not set

- apps/example-app/src/app/examples/08-directive.spec.ts
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render-template.spec.ts
Close #203 
- Add `render(template: string, options: RenderTemplateOptions)` overload
- Deprecate `render(directive, { template })` 
- Rename `directives.spec.ts` to `render-template.spec.ts`
- Update specs and examples to the new signature
- Single spec is left for validating backward-compatibility
I believe this change won't break existing tests as long as users aren't restricting `@deprecated` API usage.
> feat(testing-library): add an overload for template rendering

- .github/workflows/release.yml
- README.md
- apps/example-app/src/app/examples/09-router.ts
- nx.json
- projects/testing-library/src/lib/testing-library.ts
- release.config.js
as Git announced that main  should be your primary branch, I'm renaming all master references to main
**What**:
**Why**:
**How**:
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs)
> chore: rename main

- projects/testing-library/src/lib/testing-library.ts
This change destroys the fixture (and in turn the components) after each test. This will prevent weird errors and free the components memory.
Fixes #240
> feat: destroy fixture in cleanup (#240)

- apps/example-app-karma/src/app/issues/issue-222.spec.ts
- apps/example-app/src/app/examples/16-input-getter-setter.spec.ts
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/change.spec.ts
- projects/testing-library/tests/rerender.spec.ts
Closes #252
rerender has been renamed to change
change keeps the current fixture intact and invokes ngOnChanges
the new rerender method destroys the current component and creates a new instance
with the updated properties
BEFORE:
const { rerender } = render(...)
rerender({...})
AFTER:
const { change } = render(...)
change({...})
> feat: add rerender method

- apps/example-app/src/app/examples/02-input-output.spec.ts
- apps/example-app/src/app/examples/11-ng-content.spec.ts
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render-template.spec.ts
The template property is removed from the render options.
Instead, you can pass it as the first argument of `render.
BEFORE:
```ts
await render(InputOutputComponent, {
// 👇 this is deprecated
template: '<app-fixture [value]="47" (sendValue)="sendValue($event)" (clicked)="clicked()"></app-fixture>',
componentProperties: {
sendValue: sendSpy,
},
});
```
AFTER:
```ts
//           👇 Move the template in the first argument
await render('<app-fixture [value]="47" (sendValue)="sendValue($event)" (clicked)="clicked()"></app-fixture>', {
//               👇 Add the component to declarations
declarations: [InputOutputComponent],
componentProperties: {
sendValue: sendSpy,
},
});
```
> feat: remove RenderDirectiveOptions

- angular.json
> fix: correct peer dependencies

- apps/example-app/src/app/examples/18-html-as-input.spec.ts
- apps/example-app/src/app/issues/issue-269.spec.ts
@the-ult I've added a workaround in the test cases.
Do you see a possible solution so we don't require this workaround?
> test: add test case for #269

- apps/example-app-karma/src/test.ts
- apps/example-app/src/app/examples/01-nested-component.ts
- apps/example-app/src/app/examples/03-forms.ts
- apps/example-app/src/app/examples/04-forms-with-material.spec.ts
- apps/example-app/src/app/examples/04-forms-with-material.ts
- apps/example-app/src/app/examples/06-with-ngrx-store.ts
- apps/example-app/src/app/examples/08-directive.spec.ts
- apps/example-app/src/app/examples/12-service-component.ts
- apps/example-app/src/app/examples/15-dialog.component.spec.ts
- apps/example-app/src/app/examples/16-input-getter-setter.ts
- apps/example-app/src/app/issues/issue-254.spec.ts
- projects/testing-library/.eslintrc.json
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/auto-cleanup.spec.ts
- projects/testing-library/tests/change.spec.ts
- projects/testing-library/tests/config.spec.ts
- projects/testing-library/tests/integration.spec.ts
- projects/testing-library/tests/issues/issue-188.spec.ts
- projects/testing-library/tests/rerender.spec.ts
- tsconfig.base.json
> refactor: enable strict mode

- lint-staged.config.js
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/issues/issue-280.spec.ts
> fix: invoke initialNavigation when a router is injected

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render.spec.ts
Closes #306 
This is a first stab at adding the ability to override the `imports` metadata field for standalone components.
This PR adds the `componentImports` field to the `render` function options. These imports are used to override the existing imports on a standalone component. The reasons for completely overriding imports are:
- It's the most simple option API-wise. It's possible you could be more granular and allow the user to specify specific imports to override but this is likely overkill.
- This is more similar to the 'blank slate' model of imports that all Angular component tests used prior to standalone components where you would need to specify all your dependencies in `TestBed.configureTestModule`.
As implemented, this only works for the `render(FooComponent)` style rendering …
> feat: support componentImports option for standalone components

- projects/testing-library/src/lib/models.ts
Hello,
I noticed that since this [change](https://github.com/mateusduraes/angular-testing-library/commit/cd17373272d517057c4650d2ccc13e61b07c27a6#diff-8e35d38d4ce658063a1f7522f82a938a8b99a52223927129ad8ddd28df541506R116) the `rerender` function became an async function, meaning that now it will return a `Promise`.
However, the return type of the `rerender` function wasn't updated from `void` to `Promise<void>` so I decided to open this PR.
> Fix 'rerender' type to Promise<void>

- projects/testing-library/src/lib/testing-library.ts
> fix: invoke initialNavigation in zone

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/issues/issue-318.spec.ts
This is done to represent a more real Angular running environment
Closes #318
> fix: don't fire router events on render

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render.spec.ts
> fix: don't invoke ngOnChanges when no properties are provided

- apps/example-app-karma/src/app/issues/issue-222.spec.ts
- apps/example-app/src/app/examples/16-input-getter-setter.spec.ts
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/changeInputs.spec.ts
- projects/testing-library/tests/rerender.spec.ts
Part of #322 
`rerender` expects properties to be wrapped in an object containing `componentProperties` (or `componentInputs` and `componentOutputs` to have a more fine-grained control).
BEFORE:
```ts
await render(PersonComponent, { 
componentProperties: { 
name: 'Sarah' 
}
});
await rerender({ name: 'Sarah 2' });
```
AFTER:
```ts
await render(PersonComponent, { 
componentProperties: { 
name: 'Sarah' 
}
});
await rerender({ 
componentProperties: { 
name: 'Sarah 2' 
}
});
```
> feat: add more fine-grained control over inputs and outputs

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/fire-event.spec.ts
> feat: add ability to turn off auto detect changes

- projects/testing-library/package.json
BEFORE:
The minimum version of Angular is v14.0.0
AFTER:
The minimum version of Angular is v14.1.0
> chore: update peer dependencies

- projects/testing-library/package.json
close #333
Thanks for being open to this change. Please let me know, if I have missed something. But I think this is the only necessary change.
> build: ease integration into projects

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
The config property detectChanges is renamed to detectChangesOnRender.
BEFORE:
```ts
const component = await render(AppComponent, {
detectChanges: false
});
```
AFTER:
```ts
const component = await render(AppComponent, {
detectChangesOnRender: false
});
```
> feat: remove detectChanges in favor of detectChangesOnRender

- apps/example-app/src/app/examples/04-forms-with-material.spec.ts
- apps/example-app/src/app/examples/04-forms-with-material.ts
- apps/example-app/src/app/material.module.ts
> add checkbox example

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render.spec.ts
Added the ability to specify an initial route to render with. As someone who wanted to use my original routes in my tests, I found that even though I do initial navigation without detecting changes in my tests using navigate, I would still run into issues where my resolver would get triggered despite the fact I was switching before detecting changes.
This allows navigation to happen before the location listener is set up so that you may perform an initial route navigation without causing any resolvers/guards to run and additionally having to specify await navigate(...) in your tests
> feat: Added initialRoute parameter to avoid resolver issues with using a default route

- package.json
close #369
Cherry picking this commit into https://github.com/testing-library/angular-testing-library/pull/366 fixed its pipeline. I would like to merge this PR independently, to make clear this fix has nothing to do with it.
> fix: add types for @testing-library/jasmine-dom

- projects/testing-library/src/lib/models.ts
> docs: hint to use rerender instead

- apps/example-app/src/app/examples/02-input-output.spec.ts
- projects/testing-library/src/lib/models.ts
- projects/testing-library/tests/render.spec.ts
> docs: use fine-grained overrides in examples

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/rerender.spec.ts
feat: support ngOnChanges with correct simpleChange object within rerender
close #365
any feedback or changes are highly appreciated :)
> feat: support ngOnChanges with correct simpleChange object within rerender

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/rerender.spec.ts
> fix: calculate changes for input properties like component properties

- projects/testing-library/src/lib/models.ts
- projects/testing-library/tests/issues/issue-386.spec.ts
- projects/testing-library/tests/issues/issue-389.spec.ts
> fix: allow input properties to be aliased

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/issues/issue-396-standalone-stub-child.spec.ts
- projects/testing-library/tests/render.spec.ts
Allows a user to configure the testbed before a component is rendered.
This is flexible and useful for specific use-cases, or one-off implementations. 
Examples of this are providers/components/templates that need to be overridden (which became harder with standalone components).
Closes #396
> feat: add configureTestBed callback method

- projects/testing-library/tests/issues/issue-397-directive-overrides-component-input.spec.ts
> docs: reproduce #397

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/integrations/ng-mocks.spec.ts
- projects/testing-library/tests/render.spec.ts
The initalRoute property of the render() function will now accept query parameters. This way a component can be directly loaded in query parameters dependent state without a second navigation step.
The original navigate function is split into a external & internal function were the external function will also execute a detectChanges().
> Accept query params in initialRoute property

- README.md
This updates the all contributors badge url to the updated format, same as this change: https://github.com/testing-library/testing-library-docs/pull/1398
> docs: update all contributors badge

- projects/testing-library/package.json
`@testing-library/dom` is now a peer dependency of `@testing-library/angular`. This means that you need to install `@testing-library/dom` separately.
> feat: move dtl to peerDeps

- apps/example-app/src/app/examples/22-signal-inputs.component.spec.ts
- apps/example-app/src/app/examples/22-signal-inputs.component.ts
> docs: add computed example

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render.spec.ts
closes #462
I had to move the `renderFixture` function up the order, as it's necessary to keep track of the `subscribedOutputs` in order to not unnecessarily unsubscribe+resubscribe unchanged listeners when `rerender`ing.
> new option `on` for render and rerender

- README.md
- apps/example-app/src/app/examples/02-input-output.spec.ts
- apps/example-app/src/app/examples/22-signal-inputs.component.spec.ts
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/integrations/ng-mocks.spec.ts
- projects/testing-library/tests/render.spec.ts
- projects/testing-library/tests/rerender.spec.ts
Fixes #464 
This PR restores the type safety of inputs and introduces a new property called `inputs` and deprecates `componentInputs`. Previously we had an union with `{ [alias: string]: unknown }` which would essentially act as `any`.
We add a branded type through which aliases can be explicitly supplied.
Usage:
```ts
@Component({
selector: 'atl-fixture',
template: `<span>{{ myName() }}</span> <span>{{ myJob() }}</span>`,
})
class InputComponent {
myName = input('foo');
myJob = input('bar', { alias: 'job' });
}
it('should set the input component', async () => {
await render(InputComponent, {
inputs: {
myName: 'Bob',
job: aliasedInputWithValue('Builder'),
},
});
expect(screen.getByText('Bob')).toBeInTheDocument();
expect(screen.getByText('Builder')).toBeInTheDocument();
});
```
> refactor: stronger typing of inputs

- projects/testing-library/schematics/ng-add/index.ts
- projects/testing-library/schematics/ng-add/schema.json
- projects/testing-library/schematics/ng-add/schema.ts
This pull request if for the issues:
https://github.com/testing-library/angular-testing-library/issues/477
https://github.com/testing-library/angular-testing-library/issues/472
With this change you need to update the documentation. The way to use both is:
```sh
ng add @testing-library/angular --install-jest-dom --install-user-event
```
By default both are in false for this reason, no matter if the users are still using as documentation.
@timdeschryver
> Adding installJestDom and installUserEvent as option to the ng-add schematic

- apps/example-app/src/app/examples/22-signal-inputs.component.spec.ts
- apps/example-app/src/app/examples/22-signal-inputs.component.ts
- projects/testing-library/src/lib/models.ts
Fixes #483 
This PR adds support for `InputSignalWithTransform` in the `inputs` property added by #473.
> fix: add support for InputSignalWithTransform in inputs property

- projects/testing-library/tests/issues/issue-492.spec.ts
> docs: add test case for #492

- apps/example-app-karma/src/app/issues/issue-491.spec.ts
> docs: add test case for #491

- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
Since Angular v19, components are set as standalone: true by default, but ATL is currently supporting only non-standalone wrapper. For forward-compatibility, make default wrapper `standalone: false` explicitly.
> fix: make wrapper component `standalone: false` explicitly

- projects/testing-library/src/lib/testing-library.ts
Was exploring the codebase and noticed some small performance wins.
Hope this helps with readability and consistency!
> perf: optimize reduce and foreach loops

- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/providers/component-provider.spec.ts
Close #506
fyi: In contrast to `componentProviders`, `providers` is just passed into TestBed's module configuration. So it is treated by Angular itself and flattened correctly.
> fix: flatten component providers for consistency to the framework

- projects/testing-library/schematics/ng-add/index.ts
let Angular CLI decide which package manager to use to install the dependencies based on the configuration in `angular.json` file (default is "npm").
fixes #513
> fix: do not force npm to install dependencies when using `ng add`

- projects/testing-library/package.json
> Include @angular/animations as a peer dependency

- apps/example-app/src/app/examples/15-dialog.component.spec.ts
- apps/example-app/src/test-setup.ts
- projects/testing-library/package.json
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
- projects/testing-library/tests/render.spec.ts
Closes #525
Angular recommends using css animations, https://angular.dev/guide/animations/migration
BREAKING CHANGE
Because of the removal of the animations dependency, the `NoopAnimationsModule` is no longer automatically imported in the render function.
BEFORE:
The `NoopAnimationsModule` is always imported to the render the component.
AFTER:
Import the `NoopAnimationsModule` in your render configuration where needed:
```ts
await render(SutComponent, {
imports: [NoopAnimationsModule],
});
```
> feat: remove animations dependency

- projects/testing-library/src/lib/config.ts
- projects/testing-library/src/lib/models.ts
- projects/testing-library/src/lib/testing-library.ts
> feat: add config for testing with zoneless Angular

- projects/testing-library/src/lib/testing-library.ts
This PR fixes zoneless flag in the configure function. I tried to use the configure function with zoneless flag
```typescript
function setup() {
configure({ zoneless: true });
return render(MyComponent);
}
```
but I got error `Unexpected value 'undefined' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.`
This is because `provideZonelessChangeDetection` is incorrectly used inside `imports` instead of `providers`.
> fix: fix config for testing with zoneless Angular
